app = "techbite-news"
primary_region = "iad"

[build]
  builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  SITE_NAME = "TechBite News"
  AD_CLIENT = "ca-pub-XXXXXXXXXXXXXXXX"
